import poster1 from "../../images/movie-posters/pic__COLOR_pic1.png";
import poster2 from "../../images/movie-posters/pic__COLOR_pic2.png";
import poster3 from "../../images/movie-posters/pic__COLOR_pic3.png";
import poster4 from "../../images/movie-posters/pic__COLOR_pic4.png";
import poster5 from "../../images/movie-posters/pic__COLOR_pic5.png";
import poster6 from "../../images/movie-posters/pic__COLOR_pic6.png";
import poster7 from "../../images/movie-posters/pic__COLOR_pic7.png";
import poster8 from "../../images/movie-posters/pic__COLOR_pic8.png";
import poster9 from "../../images/movie-posters/pic__COLOR_pic9.png";
import poster10 from "../../images/movie-posters/pic__COLOR_pic10.png";
import poster11 from "../../images/movie-posters/pic__COLOR_pic11.png";
import poster12 from "../../images/movie-posters/pic__COLOR_pic12.png";

export const cardsData = [
  {
    country: "",
    director: "",
    duration: "1ч 17м",
    year: 0,
    description: "",
    image: poster1,
    trailer: "",
    nameRU: "33 слова о дизайне",
    nameEN: "",
    thumbnail: "",
    movieId: "1",
    owner: "",
    _id: 0,
  },
  {
    country: "",
    director: "",
    duration: "1ч 17м",
    year: 0,
    description: "",
    image: poster2,
    trailer: "",
    nameRU: 'Киноальманах "100 лет дизайна"',
    nameEN: "",
    thumbnail: "",
    movieId: "1",
    owner: "",
    _id: 1,
  },
  {
    country: "",
    director: "",
    duration: "1ч 17м",
    year: 0,
    description: "",
    image: poster3,
    trailer: "",
    nameRU: "В погоне за Бенкси",
    nameEN: "",
    thumbnail: "",
    movieId: "1",
    owner: "",
    _id: 2,
  },
  {
    country: "",
    director: "",
    duration: "1ч 17м",
    year: 0,
    description: "",
    image: poster4,
    trailer: "",
    nameRU: "Баския: Взрыв реальности",
    nameEN: "",
    thumbnail: "",
    movieId: "1",
    owner: "",
    _id: 3,
  },
  {
    country: "",
    director: "",
    duration: "1ч 17м",
    year: 0,
    description: "",
    image: poster5,
    trailer: "",
    nameRU: "Бег это свобода",
    nameEN: "",
    thumbnail: "",
    movieId: "1",
    owner: "",
    _id: 4,
  },
  {
    country: "",
    director: "",
    duration: "1ч 17м",
    year: 0,
    description: "",
    image: poster6,
    trailer: "",
    nameRU: "Киноторговцы",
    nameEN: "",
    thumbnail: "",
    movieId: "1",
    owner: "",
    _id: 5,
  },
  {
    country: "",
    director: "",
    duration: "1ч 17м",
    year: 0,
    description: "",
    image: poster7,
    trailer: "",
    nameRU: "Когда я думаю о Германии ночью",
    nameEN: "",
    thumbnail: "",
    movieId: "1",
    owner: "",
    _id: 6,
  },
  {
    country: "",
    director: "",
    duration: "1ч 17м",
    year: 0,
    description: "",
    image: poster8,
    trailer: "",
    nameRU: "Gimme Danger: История Игги и The Stooges",
    nameEN: "",
    thumbnail: "",
    movieId: "1",
    owner: "",
    _id: 7,
  },
  {
    country: "",
    director: "",
    duration: "1ч 17м",
    year: 0,
    description: "",
    image: poster9,
    trailer: "",
    nameRU: "Дженис: Маленькая девочка грустит",
    nameEN: "",
    thumbnail: "",
    movieId: "1",
    owner: "",
    _id: 8,
  },
  {
    country: "",
    director: "",
    duration: "1ч 17м",
    year: 0,
    description: "",
    image: poster10,
    trailer: "",
    nameRU: "Соберись перед прыжком",
    nameEN: "",
    thumbnail: "",
    movieId: "1",
    owner: "",
    _id: 9,
  },
  {
    country: "",
    director: "",
    duration: "1ч 17м",
    year: 0,
    description: "",
    image: poster11,
    trailer: "",
    nameRU: "Пи Джей Харви: A dog called money",
    nameEN: "",
    thumbnail: "",
    movieId: "1",
    owner: "",
    _id: 10,
  },
  {
    country: "",
    director: "",
    duration: "1ч 17м",
    year: 0,
    description: "",
    image: poster12,
    trailer: "",
    nameRU: "По волнам: Искусство звука в кино",
    nameEN: "",
    thumbnail: "",
    movieId: "1",
    owner: "",
    _id: 11,
  },
];
